version: '3.8'
services:
  app:
    container_name: laravel_app
    build: .
    volumes:
      - ./taskManagementApp:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: Admin
      MYSQL_PASSWORD: deem17174
      MYSQL_ROOT_PASSWORD: deem17174  
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
